load("//Config:buck_rule_macros.bzl", "apple_third_party_lib")

apple_third_party_lib(
    name = "DepsObjC",
    visibility = ["PUBLIC"],
    exported_headers = glob(["*.h"]),
    headers = glob(["*.h",]),
    srcs = glob(["*.m"])
)